spring:
  application:
    name: news

  data:
    mongodb:
      uri: ${MONGO_URI}

server:
  port: 8080

x:
  bearer-token: ${X_BEARER_TOKEN}
  client-id: ${X_CLIENT_ID}
  client-secret: ${X_CLIENT_SECRET}